language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

install:
  - travis_retry composer install

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml
